### ISSUE TITLE
Adding to the application list/menu on Linux distributions

### ISSUE THREAD

**Issue by TheStophe** [Satergo/Satergo#19]
I'm not exactly a pro yet on my mac m1 asahi (arch) linux. Any chance you'd be able to update the wiki to add download, build, and run for linux? A hand holding guide would be a huge help. 

Right now I have the files on the desktop and ./run.sh brings up the app, but not sure how to save the App in Applications?

**Comment by satsen** [comment]
Well there is only an installer for Windows, not for any other OS. The reason for there not being one for Linux distributions is because there are so many formats (deb, rpm, pkg, AppImage, flatpak, snap) and me having no experience with any of them. So I have no idea how your system works but if it uses the freedesktop desktop entry format you can create a `Satergo.desktop` which links to the application and then add that to your application list

**Comment by TheStophe** [comment]
Thanks, that all makes sense. I'll give the `Satergo.desktop` a shot and report back.

**Comment by TheStophe** [comment]
Apparently on ArchLinux the proper was is to use pacman. So I tried building it using the .tar.gz file and get the following error, where I'm in the directory containing the tar file:

```
sudo pacman -U Satergo-1.6.0.tar.gz 
loading packages...
error: missing package metadata in Satergo-1.6.0.tar.gz
error: 'Satergo-1.6.0.tar.gz': invalid or corrupted package
```

I'm still figuring out how to add an Application in Asahi Linux (ArchLinux)...learning curve on this one.

**Comment by satsen** [comment]
@ccgarant That command is for Arch Linux pacman packages (.pkg), you can't provide an archive that isn't a pacman package.

If you want to add Satergo to your user menu, the way to go is to make a Desktop Entry file (file name ends with .desktop) and add it to your menu. See: https://wiki.archlinux.org/title/Desktop_entries

**Comment by satsen** [comment]
Here, I made one:

```desktop
[Desktop Entry]
Type=Application
# The version of the desktop entry specification to which this file complies
Version=1.0
Name=Satergo
Comment=The desktop wallet for Ergo
Exec=/path-to-satergo/run.sh
Icon=/path-to-satergo/window-logo.png
Categories=Finance;Java
Keywords=ergo;crypto;cryptocurrency;wallet
```

1. Download [window-logo.png](https://github.com/Satergo/Satergo/blob/master/src/main/resources/images/window-logo.png) and put it in the Satergo directory
2. Create a file called `satergo-Satergo.desktop` (anywhere), paste that content and fill in the `path-to-satergo` with an absolute path to the Satergo directory
3. In the terminal, run `xdg-desktop-menu install satergo-Satergo.desktop`

**Comment by TheStophe** [comment]
It worked thanks!! The only thing is I renamed it after I added it to desktop from "satergo-Satergo" to "Satergo".

![Screenshot_20231008_081320](https://github.com/Satergo/Satergo/assets/25705528/4bcdc10e-69b3-4746-9a7d-9f8421b536c5)

I would say this is closed. Would def recommend adding to the wiki.
